### ISSUE TITLE
Conform FB submission to new process

### ISSUE THREAD

**Issue by nditada** [instedd/aida#173]
https://developers.facebook.com/docs/messenger-platform/app-review

**Comment by nekron** [comment]
According to facebook [pre-launch checklist](https://developers.facebook.com/docs/messenger-platform/prelaunch-checklist) and [messenger platform policies](https://developers.facebook.com/policy#messengerplatform) we should:
- [ ] be handling and logging [policy-enforcement events](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_policy_enforcement)
- [ ] respect all requests (either on Messenger or off) by people to block, discontinue, or otherwise opt-out of our using Messenger to communicate with them (surveys and scheduled messages)

We also need to:
- [ ] include [this](https://developers.facebook.com/docs/messenger-platform/prelaunch-checklist) [guides](https://developers.facebook.com/policy#messengerplatform) in AIDA-ui facebook channel setup, so the admin knows how to meet facebook's publishing requirements.
- [ ] encourage our users to maintain a Facebook Page that provides customer support contact information, including your mailing address and one or more of the following: email address, web address, or telephone number.
- [ ] remind the user that they cannot use Messenger to facilitate direct conversations between people and healthcare providers or to send or collect any patient data obtained from healthcare providers.

I'll keep updating this comment as I read their docs, then I'll create an issue for each task and keep this as an epic.

**Comment by aeatencio84** [comment]
When receiving the unsubscribe keyword, flag session as do not disturb, and ignore all outgoing scheduled messages or surveys. If an additional message is received later, reset the do not disturb flag.

**Comment by aeatencio84** [comment]
Done: unsubscribe.
In progress: policy enforcement events.

**Comment by mmuller** [comment]
Unsubscribe keyword is working properly in version 61d95e2

**Comment by aeatencio** [comment]
@nekron, when you ask for "A TLDR of the guides should be inclued in the information tooltip (...)", what kind of tooltip are you thinking of? Because I've got this tooltip style from @jkicillof (https://projects.invisionapp.com/d/main#/console/12115078/299944192/preview), but I think here we may need another kind of tooltip.

**Comment by mmuller** [comment]
Working properly in version 56c0b32
